package co.edu.campusucc.sd.modelo;
// Generated 13/04/2020 12:27:04 AM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by hbm2java
 */
public class Banco implements java.io.Serializable {

	private String idBanco;
	private Pais pais;
	private String nombre;
	private String sede;
	private String numeroCuenta;
	private Set corresponsals = new HashSet(0);
	private Set referencias = new HashSet(0);

	public Banco() {
	}

	public Banco(String idBanco) {
		this.idBanco = idBanco;
	}

	public Banco(String idBanco, Pais pais, String nombre, String sede, String numeroCuenta, Set corresponsals,
			Set referencias) {
		this.idBanco = idBanco;
		this.pais = pais;
		this.nombre = nombre;
		this.sede = sede;
		this.numeroCuenta = numeroCuenta;
		this.corresponsals = corresponsals;
		this.referencias = referencias;
	}

	public String getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(String idBanco) {
		this.idBanco = idBanco;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSede() {
		return this.sede;
	}

	public void setSede(String sede) {
		this.sede = sede;
	}

	public String getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(String numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public Set getCorresponsals() {
		return this.corresponsals;
	}

	public void setCorresponsals(Set corresponsals) {
		this.corresponsals = corresponsals;
	}

	public Set getReferencias() {
		return this.referencias;
	}

	public void setReferencias(Set referencias) {
		this.referencias = referencias;
	}

}
