package co.edu.campusucc.sd.modelo;
// Generated 13/04/2020 12:27:04 AM by Hibernate Tools 5.4.7.Final

/**
 * Corresponsal generated by hbm2java
 */
public class Corresponsal implements java.io.Serializable {

	private String idCorresponsal;
	private Banco banco;

	public Corresponsal() {
	}

	public Corresponsal(String idCorresponsal) {
		this.idCorresponsal = idCorresponsal;
	}

	public Corresponsal(String idCorresponsal, Banco banco) {
		this.idCorresponsal = idCorresponsal;
		this.banco = banco;
	}

	public String getIdCorresponsal() {
		return this.idCorresponsal;
	}

	public void setIdCorresponsal(String idCorresponsal) {
		this.idCorresponsal = idCorresponsal;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

}
