package co.edu.campusucc.sd.modelo;
// Generated 13/04/2020 12:27:04 AM by Hibernate Tools 5.4.7.Final

/**
 * Referencia generated by hbm2java
 */
public class Referencia implements java.io.Serializable {

	private String idGiro;
	private Banco banco;
	private String documento;
	private String receptor;
	private String destinatario;

	public Referencia() {
	}

	public Referencia(String idGiro) {
		this.idGiro = idGiro;
	}

	public Referencia(String idGiro, Banco banco, String documento, String receptor, String destinatario) {
		this.idGiro = idGiro;
		this.banco = banco;
		this.documento = documento;
		this.receptor = receptor;
		this.destinatario = destinatario;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public String getReceptor() {
		return this.receptor;
	}

	public void setReceptor(String receptor) {
		this.receptor = receptor;
	}

	public String getDestinatario() {
		return this.destinatario;
	}

	public void setDestinatario(String destinatario) {
		this.destinatario = destinatario;
	}

}
